### ISSUE TITLE
does gorse keep track of items recommended to each user?

### ISSUE THREAD

**Issue by outranker** [zhenghaoz/gorse#191]
In order to recommend new items to a user each time, recommendation history needs to be created for all users.

Does gorse keep track of what items have been recommended to a user?

**Comment by zhenghaoz** [comment]
Good question. There are two options:
1. Insert a read type feedback to Gorse when a item is showed to a user. This is the way our demo [zhenghaoz/gitrec](https://github.com/zhenghaoz/gitrec) track user seen recommendations.
2. Use `write-back` parameter to write back recommendations to Gorse, eg:
```bash
curl -i -H "Accept: application/json" -H "Content-Type: application/json" -X GET http://127.0.0.1:8088//api/recommend/0?write-back=read
```
The 1st option is more accurate since it is done by front end but the 2rd option is more convenient.

**Comment by IbrohimIsroilov** [comment]
In the documentation, it is said that click_feedback_types must come from recommendations of Gorse. I choose an item from the database that is not included in both latest and popular items. And I choose a user from the database for whom the item I selected is not recommended to that specific user. Then, I tried to insert a feedback whose feedback_type is click by that specific user to that specific item. It still works. The feedback was successfully inserted to the databaase. But I don't understand. Because in my opinion the feedback should not be inserted as it is not recommend by gorse. I don't understand that part. What is the point of tracking  click_feedback_types? Can you explain it?

**Comment by zhenghaoz** [comment]
I think the name `click_feedback_types` is confusing. Maybe we need to rename it to `target_feedback_types`. `click_feedback_types` is used for online evaluation. It means this user is happy about recommended items. This is the reason that feedbacks from other sources shouldn't be added as `click_feedback_types`. It might break online evaluation.

**Comment by zhenghaoz** [comment]
This issue is closed since click feedback types have been removed in c80234df429d787c6ab910e493a8f37a932faf07.
